// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG8k-tep0oWJYJcLdEODAkjwqjIu2KZmU',
    appId: '1:47857730961:web:52bc9fc442ae93fd8a8630',
    messagingSenderId: '47857730961',
    projectId: 'fir-app-sample-24a04',
    authDomain: 'fir-app-sample-24a04.firebaseapp.com',
    storageBucket: 'fir-app-sample-24a04.appspot.com',
    measurementId: 'G-Y5N43WFF3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAovCkP1xXj_zS8zSApgzvN2mTwuaox1-I',
    appId: '1:47857730961:android:08a970eb0568a5d78a8630',
    messagingSenderId: '47857730961',
    projectId: 'fir-app-sample-24a04',
    storageBucket: 'fir-app-sample-24a04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoPmzeocFV42ttbS291JdIs_tKsfU2v7w',
    appId: '1:47857730961:ios:247392b86ee39d668a8630',
    messagingSenderId: '47857730961',
    projectId: 'fir-app-sample-24a04',
    storageBucket: 'fir-app-sample-24a04.appspot.com',
    iosClientId: '47857730961-sdlocgul25qu2hlfhftjj3gqka1udbkr.apps.googleusercontent.com',
    iosBundleId: 'com.nurika.firebaseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoPmzeocFV42ttbS291JdIs_tKsfU2v7w',
    appId: '1:47857730961:ios:247392b86ee39d668a8630',
    messagingSenderId: '47857730961',
    projectId: 'fir-app-sample-24a04',
    storageBucket: 'fir-app-sample-24a04.appspot.com',
    iosClientId: '47857730961-sdlocgul25qu2hlfhftjj3gqka1udbkr.apps.googleusercontent.com',
    iosBundleId: 'com.nurika.firebaseapp',
  );
}
